export interface BuddhistCenter {
  id: string;
  rank: number;
  name: string;
  description: string;
  type: "monastery" | "meditation-center" | "temple" | "buddhist-center" | "retreat-center";
  location: string;
  country: string;
  image?: string;
  members: number;
  rating: number;
  status: "open" | "closed" | "retreat" | "by-appointment";
  featured: boolean;
  website?: string;
  phone?: string;
  email?: string;
  tags: string[];
  accentColor: string;
}

export const buddhistCenters: BuddhistCenter[] = [
  {
    id: "chua-quang-minh",
    rank: 1,
    name: "Chùa Quang Minh",
    description: "Vietnamese Buddhist temple serving the Atlanta community with traditional practices and ceremonies. A peaceful sanctuary for meditation and dharma study.",
    type: "temple",
    location: "Atlanta, GA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__7ac90348.jpg",
    members: 850,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "http://www.chuaquangminh.org",
    tags: ["Vietnamese", "Temple", "Meditation", "Community"],
    accentColor: "#d4af37",
  },
  {
    id: "chua-thien-an",
    rank: 2,
    name: "Chùa Thiên Ân (Desert Zen Center)",
    description: "Zen monastery in the California desert offering authentic Zen practice and retreats. A remote sanctuary for deep meditation practice.",
    type: "monastery",
    location: "Lucerne Valley, CA",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__7405792d.jpg",
    members: 420,
    rating: 4.9,
    status: "retreat",
    featured: true,
    website: "http://www.desertzencenter.org",
    tags: ["Zen", "Monastery", "Retreat", "Desert"],
    accentColor: "#c9a66b",
  },
  {
    id: "chua-buu-mon",
    rank: 3,
    name: "Chùa Bửu Môn",
    description: "Traditional Vietnamese Buddhist temple in Port Arthur serving the local Vietnamese American community with regular dharma talks and ceremonies.",
    type: "temple",
    location: "Port Arthur, TX",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__de85f2b1.jpg",
    members: 520,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "http://www.buumon.org",
    tags: ["Vietnamese", "Temple", "Community", "Texas"],
    accentColor: "#8bc9a8",
  },
  {
    id: "chua-tam-bao-tulsa",
    rank: 4,
    name: "Chùa Tam Bảo – Tulsa",
    description: "Vietnamese Buddhist temple in Tulsa offering traditional practices, meditation classes, and cultural events for the local sangha.",
    type: "temple",
    location: "Tulsa, OK",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__faf500b9.jpg",
    members: 380,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://ducquanam.com",
    tags: ["Vietnamese", "Temple", "Meditation", "Oklahoma"],
    accentColor: "#7bb89b",
  },
  {
    id: "tam-bao-baton-rouge",
    rank: 5,
    name: "Chùa Tam Bảo – Baton Rouge",
    description: "Meditation center dedicated to mindfulness practice and dharma study. Offers regular meditation sessions and Buddhist teachings.",
    type: "meditation-center",
    location: "Baton Rouge, LA",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__cf7ae198.jpg",
    members: 290,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://www.batonrougebuddha.org",
    tags: ["Meditation", "Mindfulness", "Vietnamese", "Louisiana"],
    accentColor: "#6ba3d4",
  },
  {
    id: "chua-linh-son-austin",
    rank: 6,
    name: "Chùa Linh Sơn – Austin",
    description: "Vietnamese Buddhist temple in Austin providing spiritual guidance, meditation practice, and community services for the Vietnamese American community.",
    type: "temple",
    location: "Austin, TX",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__9ceb6f2c.jpg",
    members: 680,
    rating: 4.7,
    status: "open",
    featured: true,
    website: "http://www.linhsonaustin.org",
    tags: ["Vietnamese", "Temple", "Austin", "Community"],
    accentColor: "#d47b6b",
  },
  {
    id: "chua-tu-hieu",
    rank: 7,
    name: "Chùa Từ Hiếu Buddhist Cultural Center",
    description: "Buddhist cultural center preserving Vietnamese Buddhist traditions and culture. Offers dharma classes, meditation, and cultural programs.",
    type: "buddhist-center",
    location: "Buffalo, NY",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__ab8f0638.jpg",
    members: 340,
    rating: 4.5,
    status: "open",
    featured: false,
    website: "http://chuatuhieu.org",
    tags: ["Vietnamese", "Cultural Center", "Buddhism", "New York"],
    accentColor: "#9b7bb8",
  },
  {
    id: "thien-vien-bo-de",
    rank: 8,
    name: "Thiền Viện Bồ Đề",
    description: "Zen meditation center in Massachusetts offering authentic Vietnamese Zen practice, meditation retreats, and dharma teachings.",
    type: "meditation-center",
    location: "Braintree, MA",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__6bac2a5c.jpg",
    members: 450,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://tvbode.com",
    tags: ["Zen", "Meditation", "Vietnamese", "Massachusetts"],
    accentColor: "#6b9bc9",
  },
  {
    id: "chua-tuong-van",
    rank: 9,
    name: "Chùa Tường Vân",
    description: "Traditional Vietnamese temple in Lowell serving the local Buddhist community with regular ceremonies, meditation sessions, and dharma talks.",
    type: "temple",
    location: "Lowell, MA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__17b345da.jpg",
    members: 520,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://chuatuongvan.com",
    tags: ["Vietnamese", "Temple", "Community", "Lowell"],
    accentColor: "#b87b9b",
  },
  {
    id: "chua-kim-quang",
    rank: 10,
    name: "Chùa Kim Quang",
    description: "Vietnamese Buddhist temple in Sacramento providing spiritual services, meditation practice, and cultural activities for the Vietnamese community.",
    type: "temple",
    location: "Sacramento, CA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__5a54978c.jpg",
    members: 740,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "http://phexbach.wixsite.com/kimquang",
    tags: ["Vietnamese", "Temple", "California", "Sacramento"],
    accentColor: "#d4a574",
  },
  {
    id: "chua-giac-hoang",
    rank: 11,
    name: "Chùa Giác Hoàng",
    description: "Vietnamese Buddhist temple in Washington DC serving the capital area Vietnamese Buddhist community with traditional practices and teachings.",
    type: "temple",
    location: "Washington, DC",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__27f29f57.jpg",
    members: 620,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://chuagiachoangdc.org",
    tags: ["Vietnamese", "Temple", "Washington DC", "Community"],
    accentColor: "#8b9bb8",
  },
  {
    id: "chua-huong-dao",
    rank: 12,
    name: "Chùa Hương Đạo",
    description: "Vietnamese temple in Fort Worth offering traditional Buddhist ceremonies, meditation classes, and community gatherings for spiritual growth.",
    type: "temple",
    location: "Fort Worth, TX",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__509b3e92.jpg",
    members: 470,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "http://chuahuongdao.org",
    tags: ["Vietnamese", "Temple", "Texas", "Fort Worth"],
    accentColor: "#7bb89b",
  },
  {
    id: "tu-vien-cat-trang",
    rank: 13,
    name: "Tu Viện Cát Trắng (White Sands Buddhist Center)",
    description: "Buddhist monastery in Florida dedicated to meditation practice and dharma study. Offers residential programs and retreats.",
    type: "monastery",
    location: "Mims, FL",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__2cb1000a.jpg",
    members: 180,
    rating: 4.9,
    status: "retreat",
    featured: true,
    website: "https://www.tvct.org",
    tags: ["Monastery", "Retreat", "Vietnamese", "Florida"],
    accentColor: "#c9a66b",
  },
  {
    id: "chua-linh-son-worcester",
    rank: 14,
    name: "Chùa Linh Sơn – Worcester",
    description: "Vietnamese temple in Worcester providing spiritual guidance, meditation practice, and preserving Vietnamese Buddhist cultural traditions.",
    type: "temple",
    location: "Worcester, MA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__aa2de530.jpg",
    members: 390,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "https://linhsonmass.org",
    tags: ["Vietnamese", "Temple", "Massachusetts", "Worcester"],
    accentColor: "#d47b6b",
  },
  {
    id: "ni-vien-pho-hien",
    rank: 15,
    name: "Ni Viện Phổ Hiền",
    description: "Vietnamese Buddhist nunnery offering a peaceful environment for meditation practice and dharma study. Home to dedicated nuns practicing the dharma.",
    type: "monastery",
    location: "Port Orange, FL",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__ae58db11.jpg",
    members: 150,
    rating: 4.8,
    status: "by-appointment",
    featured: false,
    website: "https://nivienphohien.com",
    tags: ["Nunnery", "Vietnamese", "Meditation", "Florida"],
    accentColor: "#9b7bb8",
  },
  {
    id: "chua-dia-tang-vien-quang",
    rank: 16,
    name: "Chùa Địa Tạng Viên Quang",
    description: "Ksitigarbha Temple in Washington state serving the Pacific Northwest Vietnamese Buddhist community with traditional ceremonies and teachings.",
    type: "temple",
    location: "Lynnwood, WA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__faf500b9.jpg",
    members: 560,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "http://www.diatangtemple.org",
    tags: ["Vietnamese", "Temple", "Washington", "Pacific Northwest"],
    accentColor: "#6ba3d4",
  },
  {
    id: "dai-niem-xu-thien-vien",
    rank: 17,
    name: "Đại Niệm Xứ Thiền Viện",
    description: "Zen monastery in Florida dedicated to serious meditation practice and retreat programs. Offers long-term residency for committed practitioners.",
    type: "monastery",
    location: "Leesburg, FL",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__c95bde3d.jpg",
    members: 220,
    rating: 4.9,
    status: "retreat",
    featured: true,
    website: "https://www.dainiemxutv.org",
    tags: ["Zen", "Monastery", "Retreat", "Meditation"],
    accentColor: "#8bc9a8",
  },
  {
    id: "chua-quang-nghiem",
    rank: 18,
    name: "Chùa Quang Nghiêm",
    description: "Vietnamese Buddhist temple in Stockton providing spiritual services, meditation classes, and community support for the Central Valley Vietnamese community.",
    type: "temple",
    location: "Stockton, CA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__de85f2b1.jpg",
    members: 640,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "http://quangnghiem.org",
    tags: ["Vietnamese", "Temple", "California", "Community"],
    accentColor: "#d4af37",
  },
  {
    id: "chua-bat-nha",
    rank: 19,
    name: "Chùa Bát Nhã",
    description: "Vietnamese Buddhist temple in Orange County offering traditional ceremonies, meditation practice, and dharma education for the local sangha.",
    type: "temple",
    location: "Santa Ana, CA",
    country: "United States",
    image: "@assets/stock_images/vietnamese_buddhist__9ceb6f2c.jpg",
    members: 890,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://chuabatnhacali.org",
    tags: ["Vietnamese", "Temple", "Orange County", "Southern California"],
    accentColor: "#b87b9b",
  },
  {
    id: "tu-vien-kim-son",
    rank: 20,
    name: "Tu Viện Kim Sơn",
    description: "Large Vietnamese Buddhist monastery in Northern California offering comprehensive Buddhist education, meditation retreats, and monastic training.",
    type: "monastery",
    location: "Watsonville, CA",
    country: "United States",
    image: "@assets/stock_images/buddhist_meditation__69b277e9.jpg",
    members: 1200,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://www.kimson.org",
    tags: ["Monastery", "Vietnamese", "Retreat", "Education"],
    accentColor: "#6b9bd4",
  },
];
