// Optimized WebP images reused as neutral visual placeholders for AI/Buddhism discovery cards.
import img1 from "@assets/stock_images/vietnamese_buddhist__7ac90348.webp";
import img2 from "@assets/stock_images/buddhist_meditation__7405792d.webp";
import img3 from "@assets/stock_images/vietnamese_buddhist__de85f2b1.webp";
import img4 from "@assets/stock_images/vietnamese_buddhist__faf500b9.webp";
import img5 from "@assets/stock_images/buddhist_meditation__cf7ae198.webp";
import img6 from "@assets/stock_images/vietnamese_buddhist__9ceb6f2c.webp";
import img7 from "@assets/stock_images/vietnamese_buddhist__ab8f0638.webp";
import img8 from "@assets/stock_images/buddhist_meditation__6bac2a5c.webp";
import img9 from "@assets/stock_images/vietnamese_buddhist__17b345da.webp";
import img10 from "@assets/stock_images/vietnamese_buddhist__5a54978c.webp";

export interface BuddhistCenter {
  id: string;
  rank: number;
  name: string;
  description: string;
  type: "ai-dharma" | "robotics" | "research" | "temple" | "buddhist-organization";
  location: string;
  country: string;
  image?: string;
  members: number;
  rating: number;
  status: "open" | "closed" | "retreat" | "by-appointment";
  featured: boolean;
  website?: string;
  phone?: string;
  email?: string;
  tags: string[];
  accentColor: string;
}

export const buddhistCenters: BuddhistCenter[] = [
  {
    id: "central-monastic-body-bhutan-buddhabot",
    rank: 1,
    name: "Bhutan Central Monastic Body x BuddhaBot-Plus",
    description: "Bhutan's Central Monastic Body is piloting BuddhaBot-Plus with Kyoto University and Teraverse so monks and nuns can explore Buddhist philosophy through a generative AI dialogue system.",
    type: "buddhist-organization",
    location: "Thimphu",
    country: "Bhutan",
    image: img1,
    members: 200,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://www.kyoto-u.ac.jp/en/news/2025-03-03",
    tags: ["BuddhaBot-Plus", "Monastic education", "Generative AI", "Bhutan"],
    accentColor: "#d4af37",
  },
  {
    id: "prajina-mita-ai",
    rank: 2,
    name: "Prajina Cultural Research Association / Mita AI",
    description: "Prajina combines Tibetan Buddhist scholarship with AI engineering, building Mita AI, OCR, translation, and Dharma-debate tools with partners connected to the great Tibetan monasteries in South India.",
    type: "ai-dharma",
    location: "Taipei",
    country: "Taiwan",
    image: img2,
    members: 300,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://prajina.org/en/",
    tags: ["Tibetan Buddhism", "Mita AI", "Translation", "Digital preservation"],
    accentColor: "#6ba3d4",
  },
  {
    id: "norbu-ai-ibc",
    rank: 3,
    name: "NORBU AI / International Buddhist Confederation",
    description: "NORBU is a multilingual Buddhist AI assistant for Dharma learning, described as a spiritual friend and supported by the International Buddhist Confederation as global patron.",
    type: "buddhist-organization",
    location: "International",
    country: "Global",
    image: img3,
    members: 1000,
    rating: 4.7,
    status: "open",
    featured: true,
    website: "https://anitya.org/media/norbu-ai-revolutionary-buddhist-chatbot-for-empowering-dharma-learning/",
    tags: ["Dharma chatbot", "Multilingual", "IBC", "Learning"],
    accentColor: "#8bc9a8",
  },
  {
    id: "kinrara-metta-norbu",
    rank: 4,
    name: "Kinrara Metta Buddhist Society / NORBU",
    description: "Kinrara Metta Buddhist Society made NORBU available to its community as a Buddhist AI chatbot trained across Theravada, Mahayana, and Vajrayana content.",
    type: "temple",
    location: "Puchong",
    country: "Malaysia",
    image: img4,
    members: 450,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://kinrarametta.org/norbu-the-buddhist-chatbot/",
    tags: ["Temple adoption", "NORBU", "ChatGPT", "Dharma Q&A"],
    accentColor: "#7bb89b",
  },
  {
    id: "kodaiji-mindar",
    rank: 5,
    name: "Kodaiji Temple / Android Kannon Mindar",
    description: "Kodaiji Temple in Kyoto uses Mindar, an android Kannon created with Osaka University robotics researchers, to present Heart Sutra teachings through robotics and projection mapping.",
    type: "robotics",
    location: "Kyoto",
    country: "Japan",
    image: img5,
    members: 900,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://www.kodaiji.com/mindar/",
    tags: ["Robot preacher", "Kannon", "Heart Sutra", "Osaka University"],
    accentColor: "#c9a66b",
  },
  {
    id: "jogyesa-gabi",
    rank: 6,
    name: "Jogyesa Temple / Gabi Robot Monk",
    description: "Jogyesa Temple and the Jogye Order introduced Gabi, a humanoid robot monk, as part of a broader effort to explore Buddhist ethics, robotics, and youth engagement.",
    type: "robotics",
    location: "Seoul",
    country: "South Korea",
    image: img6,
    members: 1200,
    rating: 4.7,
    status: "open",
    featured: true,
    website: "https://www.buddhistdoor.net/news/ai-humanoid-robot-gabi-takes-precept-vows-at-buddhist-temple-in-south-korea/",
    tags: ["Robot monk", "Jogye Order", "AI ethics", "Youth outreach"],
    accentColor: "#d47b6b",
  },
  {
    id: "kyoto-university-buddhabot",
    rank: 7,
    name: "Kyoto University / BuddhaBot Research",
    description: "Kyoto University's Future of Human and Society research group develops BuddhaBot and BuddhaBot-Plus, Buddhist dialogue AI systems for ethical and doctrinal exploration.",
    type: "research",
    location: "Kyoto",
    country: "Japan",
    image: img7,
    members: 120,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://ifohs.kyoto-u.ac.jp/en/archives/37031",
    tags: ["Research", "BuddhaBot", "Ethical AI", "Dialogue AI"],
    accentColor: "#9b7bb8",
  },
  {
    id: "buddharoid-shoren-in",
    rank: 8,
    name: "Buddharoid / Shoren-in Temple Demonstration",
    description: "The Buddharoid project demonstrated an AI-integrated robot monk at Shoren-in Temple, combining BuddhaBot-Plus with a humanoid interface for Buddhist guidance.",
    type: "robotics",
    location: "Kyoto",
    country: "Japan",
    image: img8,
    members: 160,
    rating: 4.6,
    status: "by-appointment",
    featured: false,
    website: "https://ifohs.kyoto-u.ac.jp/en/archives/37637",
    tags: ["Buddharoid", "Robot monk", "BuddhaBot-Plus", "Temple demo"],
    accentColor: "#6b9bc9",
  },
  {
    id: "mountain-view-buddhist-temple-ai-dharma",
    rank: 9,
    name: "Mountain View Buddhist Temple / AI Dharma Talk",
    description: "Mountain View Buddhist Temple, part of Buddhist Churches of America, published and reflected on a Dharma talk drafted with ChatGPT as an experiment in AI-assisted Buddhist teaching.",
    type: "temple",
    location: "Mountain View, CA",
    country: "United States",
    image: img9,
    members: 650,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "https://mvbuddhisttemple.org/chatbots-dharma-talk/",
    tags: ["ChatGPT", "Jodo Shinshu", "Dharma talk", "BCA"],
    accentColor: "#b87b9b",
  },
  {
    id: "ai-buddha-zen",
    rank: 10,
    name: "AI Buddha Zen",
    description: "AI Buddha Zen is a Buddhist AI chat service on LINE and iOS that uses retrieval-augmented generation over 10,000+ scripture verses and includes citation and safety safeguards.",
    type: "ai-dharma",
    location: "Tokyo",
    country: "Japan",
    image: img10,
    members: 5000,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://buddha.aimomentz.ai/?lang=en",
    tags: ["RAG", "Scripture citations", "LINE", "Safety"],
    accentColor: "#d4a574",
  },
  {
    id: "bdrc-khyentse-ai-datasets",
    rank: 11,
    name: "BDRC / Khyentse Foundation AI Datasets",
    description: "The Buddhist Digital Resource Center, with Khyentse Foundation support, is building open Tibetan Buddhist datasets, OCR models, and catalog metadata so AI systems can learn from authoritative Buddhist sources.",
    type: "buddhist-organization",
    location: "Cambridge, MA",
    country: "United States",
    image: img1,
    members: 3500,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://www.bdrc.io/blog/2026/02/28/bdrc-launches-major-initiative-to-build-open-buddhist-datasets-for-ai/",
    tags: ["Open datasets", "Tibetan OCR", "Khyentse Foundation", "AI training"],
    accentColor: "#8b9bb8",
  },
  {
    id: "tsadra-dharma-ai",
    rank: 12,
    name: "Tsadra Foundation / Dharma AI Project",
    description: "Tsadra Foundation is collaborating with the Berkeley Mitra team on a three-year effort to develop AI tools for Tibetan Buddhist translation and research while preserving doctrinal integrity.",
    type: "buddhist-organization",
    location: "Boulder, CO",
    country: "United States",
    image: img2,
    members: 800,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://www.tsadra.org/ai-tools-for-tibetan-buddhist-translation/",
    tags: ["Tibetan translation", "Dharmamitra", "Research tools", "Scholar support"],
    accentColor: "#6b9bd4",
  },
  {
    id: "dharmamitra-berkeley",
    rank: 13,
    name: "Dharmamitra / Berkeley Mitra",
    description: "Dharmamitra integrates AI with classical Buddhist text databases for translation, OCR, semantic search, and digital philology across Pali, Sanskrit, Tibetan, and Buddhist Chinese.",
    type: "research",
    location: "Berkeley, CA",
    country: "United States",
    image: img3,
    members: 600,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://dharmamitra.github.io/dharmamitra-guides/",
    tags: ["OCR", "Semantic search", "Machine translation", "Digital philology"],
    accentColor: "#7bb89b",
  },
  {
    id: "fo-guang-shan-mitra",
    rank: 14,
    name: "Fo Guang Shan Institute of Humanistic Buddhism / MITRA",
    description: "Fo Guang Shan Institute of Humanistic Buddhism signed an agreement with UC Berkeley's MITRA Project to develop multilingual Buddhist AI translation tools using Humanistic Buddhism corpora.",
    type: "buddhist-organization",
    location: "Kaohsiung",
    country: "Taiwan",
    image: img4,
    members: 2000,
    rating: 4.8,
    status: "open",
    featured: true,
    website: "https://www.fgsihb.org/news-event/news/TSNews-000317/?__locale=en",
    tags: ["Fo Guang Shan", "MITRA", "Humanistic Buddhism", "AI translation"],
    accentColor: "#d4af37",
  },
  {
    id: "rctbt-ai-reading-platform",
    rank: 15,
    name: "RCTBT / AI-Powered Buddhist Reading Platform",
    description: "The Research Centre for Translation of Buddhist Texts at the Hang Seng University of Hong Kong is developing an AI-powered digital reading platform for Buddhist translations.",
    type: "research",
    location: "Hong Kong",
    country: "China",
    image: img5,
    members: 260,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "https://rctbt.org/",
    tags: ["Buddhist translation", "Digital reading", "Sukhavati", "Research"],
    accentColor: "#9b7bb8",
  },
  {
    id: "pecha-ai-studio",
    rank: 16,
    name: "Pecha AI Studio",
    description: "Pecha AI Studio provides AI-powered tools for Buddhist studies, including Tibetan translation editing, annotation workflows, model evaluation, and future collation tools.",
    type: "ai-dharma",
    location: "International",
    country: "Global",
    image: img6,
    members: 500,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "https://pecha.ai/",
    tags: ["Tibetan texts", "Annotation", "CAT tools", "Buddhist studies"],
    accentColor: "#d47b6b",
  },
  {
    id: "buddhism-ai-initiative",
    rank: 17,
    name: "Buddhism & AI Initiative",
    description: "The Buddhism & AI Initiative maps the emerging field, convenes Buddhist-AI dialogues, and supports collaborative projects applying Buddhist wisdom to AI futures.",
    type: "buddhist-organization",
    location: "International",
    country: "Global",
    image: img7,
    members: 400,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://www.engagedbuddhists.ai/",
    tags: ["Field mapping", "Convening", "AI ethics", "Engaged Buddhism"],
    accentColor: "#6b9bc9",
  },
  {
    id: "tripitaka-mcp",
    rank: 18,
    name: "Tripitaka MCP",
    description: "Tripitaka MCP makes the Pali Canon available to AI agents through MCP, enabling segment-level search, citation, translation comparison, and Pali dictionary lookup as Dhamma Dana.",
    type: "ai-dharma",
    location: "Bangkok",
    country: "Thailand",
    image: img8,
    members: 444,
    rating: 4.7,
    status: "open",
    featured: false,
    website: "https://tripitaka-mcp.com/",
    tags: ["Pali Canon", "MCP", "SuttaCentral data", "Dhamma Dana"],
    accentColor: "#8bc9a8",
  },
  {
    id: "buddhaur-ai-teacher",
    rank: 19,
    name: "BuddhaUR / AI Buddhist Teacher",
    description: "BuddhaUR is an early-Buddhist learning app with an AI teacher grounded in cited sutta passages, structured lessons, quizzes, and adaptive practice.",
    type: "ai-dharma",
    location: "United States",
    country: "United States",
    image: img9,
    members: 1200,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://apps.apple.com/jp/app/buddhaur-buddhist-meditation/id6752915041?l=en-US",
    tags: ["Suttas", "AI teacher", "Citations", "Early Buddhism"],
    accentColor: "#b87b9b",
  },
  {
    id: "fojin-buddhist-text-platform",
    rank: 20,
    name: "FoJin Buddhist Digital Text Platform",
    description: "FoJin aggregates Buddhist digital heritage with AI Q&A, RAG citations, knowledge graphs, LLM-verified cross-canon alignment, and multi-language parallel reading.",
    type: "research",
    location: "International",
    country: "Global",
    image: img10,
    members: 10500,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://github.com/xr843/fojin",
    tags: ["RAG", "Knowledge graph", "Cross-canon", "Digital texts"],
    accentColor: "#d4a574",
  },
  {
    id: "84000-ai-ethics",
    rank: 21,
    name: "84000 / Buddhist Wisdom and AI Ethics",
    description: "84000 is actively examining AI, machine translation, and Buddhist transmission, including approved AI support use cases and workshops connecting Buddhist wisdom with AI ethics.",
    type: "buddhist-organization",
    location: "International",
    country: "Global",
    image: img1,
    members: 84000,
    rating: 4.9,
    status: "open",
    featured: true,
    website: "https://84000.co/documentation/84000s-position-on-ai-and-the-machine-translation-of-canonical-literature",
    tags: ["AI ethics", "Canonical translation", "Human-led review", "Tibetan canon"],
    accentColor: "#8b9bb8",
  },
  {
    id: "askbuddha-ai",
    rank: 22,
    name: "AskBuddha-AI",
    description: "AskBuddha-AI offers Dharma-inspired conversational reflection for mindfulness, compassion, and everyday questions, with clear boundaries that it is not a replacement for teachers or practice.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img2,
    members: 900,
    rating: 4.5,
    status: "open",
    featured: false,
    website: "https://www.askbuddha-ai.com/",
    tags: ["Reflection", "Mindfulness", "Dharma-inspired", "AI companion"],
    accentColor: "#6ba3d4",
  },
  {
    id: "buddha-answers",
    rank: 23,
    name: "Buddha Answers",
    description: "Buddha Answers provides AI-generated Buddhist Q&A grounded in the earliest scriptures, keeping canonical passages and citations visible so users can verify answers.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img3,
    members: 1200,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://buddhaanswers.com/",
    tags: ["Pali Canon", "Sutta citations", "Q&A", "Early Buddhism"],
    accentColor: "#8bc9a8",
  },
  {
    id: "eightfold-path-ai-learning",
    rank: 24,
    name: "Eightfold Path AI Learning",
    description: "Eightfold Path combines Buddhist learning content with real-time AI questions, drawing from Secular Buddhism Podcast transcripts, books, courses, and essays.",
    type: "ai-dharma",
    location: "Online",
    country: "United States",
    image: img4,
    members: 2000,
    rating: 4.5,
    status: "open",
    featured: false,
    website: "https://www.eightfoldpath.com/",
    tags: ["Buddhist learning", "AI Q&A", "Secular Buddhism", "Courses"],
    accentColor: "#7bb89b",
  },
  {
    id: "dharma-gpt-buddhist-wisdom",
    rank: 25,
    name: "DharmaGPT / Buddhist & Vedic Wisdom",
    description: "DharmaGPT is an AI spiritual assistant for questions, scripture interpretation, and daily practices across Vedic, Buddhist, and Sanatan Dharma teachings.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img5,
    members: 1800,
    rating: 4.4,
    status: "open",
    featured: false,
    website: "https://thedharmagpt.com/",
    tags: ["Buddhist wisdom", "Scripture interpretation", "Spiritual AI", "Daily practice"],
    accentColor: "#c9a66b",
  },
  {
    id: "buddhagpt-daily-inspiration",
    rank: 26,
    name: "BuddhaGPT Daily Inspiration",
    description: "BuddhaGPT is an Android AI chat app for Buddhist Q&A, daily inspiration, meditation guidance, Buddhist ethics, history, and general Dharma education.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img6,
    members: 500,
    rating: 4.3,
    status: "open",
    featured: false,
    website: "https://play.google.com/store/apps/details?id=com.buddhismgpt",
    tags: ["Android", "Buddhist Q&A", "Daily inspiration", "Meditation"],
    accentColor: "#d47b6b",
  },
  {
    id: "webuddhist-ai-studio",
    rank: 27,
    name: "WeBuddhist AI Studio",
    description: "WeBuddhist AI Studio offers AI-powered Buddhist studies tools for translation, annotation, manuscript analysis, model challenge workflows, and training-data preparation.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img7,
    members: 650,
    rating: 4.5,
    status: "open",
    featured: false,
    website: "https://buddhistai.tools/",
    tags: ["Translation", "Annotation", "Training data", "Manuscripts"],
    accentColor: "#9b7bb8",
  },
  {
    id: "cbeta-digital-ai-humanities",
    rank: 28,
    name: "CBETA / Digital Buddhist Texts for AI Humanities",
    description: "CBETA Foundation maintains one of the largest Chinese Buddhist digital text archives, a major source base for Buddhist digital humanities and downstream AI research projects.",
    type: "research",
    location: "Taipei",
    country: "Taiwan",
    image: img8,
    members: 30000,
    rating: 4.8,
    status: "open",
    featured: false,
    website: "https://cbeta.org/about",
    tags: ["Chinese canon", "Digital humanities", "Text archive", "AI source data"],
    accentColor: "#6b9bc9",
  },
  {
    id: "gotama-ai",
    rank: 29,
    name: "Gotama AI",
    description: "Gotama is an AI companion grounded in the Atthakavagga, offering daily practice, early Buddhist verses, Pali references, and conversational reflection rooted in primary texts.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img9,
    members: 1500,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://www.gotama.ai/",
    tags: ["Atthakavagga", "Early Buddhism", "Daily practice", "Pali references"],
    accentColor: "#d4af37",
  },
  {
    id: "deerpark-ai-tripitaka",
    rank: 30,
    name: "Deerpark AI / AI Tripitaka",
    description: "Deerpark AI is an AI Tripitaka reader and chatbot for 14,000 volumes of Buddhist texts, combining classical Chinese scripture with modern-language explanations.",
    type: "ai-dharma",
    location: "Online",
    country: "China",
    image: img10,
    members: 4800,
    rating: 4.6,
    status: "open",
    featured: false,
    website: "https://deerpark.ai/",
    tags: ["Tripitaka", "Chinese canon", "GPT-4", "Modern translation"],
    accentColor: "#8bc9a8",
  },
  {
    id: "sutra-listening-ai-monk",
    rank: 31,
    name: "Sutra Listening / AI Monk",
    description: "Sutra Listening is a mobile Buddhist practice app with an AI Monk, sutra listening, teachings, quizzes, prayer beads, breathing practice, and multilingual support.",
    type: "ai-dharma",
    location: "Online",
    country: "South Korea",
    image: img1,
    members: 700,
    rating: 4.4,
    status: "open",
    featured: false,
    website: "https://apps.apple.com/us/app/sutra-listening-ai-monk/id6736872122",
    tags: ["AI Monk", "Sutra audio", "Korean Buddhism", "Practice app"],
    accentColor: "#d47b6b",
  },
  {
    id: "kata-tibetan-translation",
    rank: 32,
    name: "KATA Tibetan Translation",
    description: "KATA applies neural machine translation, semantic analysis, and high-precision Tibetan OCR to Tibetan, Sanskrit, and multilingual translation for Buddhist studies and classical literature.",
    type: "research",
    location: "Online",
    country: "Global",
    image: img2,
    members: 900,
    rating: 4.5,
    status: "open",
    featured: false,
    website: "https://apps.apple.com/us/app/kata-tibetan-translation/id6757205139",
    tags: ["Tibetan OCR", "Sanskrit", "Neural translation", "Buddhist studies"],
    accentColor: "#9b7bb8",
  },
  {
    id: "buddai-enlightened-ai",
    rank: 33,
    name: "Buddai / Enlightened AI",
    description: "Buddai is a Buddhist-wisdom AI project positioning itself around mindful, compassionate, non-judgmental guidance and conscious living.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img3,
    members: 300,
    rating: 4.3,
    status: "by-appointment",
    featured: false,
    website: "https://www.buddai.com/",
    tags: ["Buddhist wisdom", "Mindful AI", "Compassion", "Waitlist"],
    accentColor: "#6ba3d4",
  },
  {
    id: "agape-ai-buddhist-guide",
    rank: 34,
    name: "Agape AI / Buddhist Guide",
    description: "Agape AI is a multi-faith AI platform that includes a Buddhist guide alongside other traditions, with an emphasis on each tradition speaking in its own voice.",
    type: "ai-dharma",
    location: "Online",
    country: "Global",
    image: img4,
    members: 1000,
    rating: 4.4,
    status: "open",
    featured: false,
    website: "https://agapeai.org/",
    tags: ["Multi-faith", "Buddhist guide", "Comparative religion", "AI ethics"],
    accentColor: "#7bb89b",
  },
];
